### ISSUE TITLE
FreeBSD - error: no member named 'sftp_client_confirm_res ume' in 'union remmina_masterthread_exec_data

### ISSUE THREAD

**Issue by mike-pt** [FreeRDP/Remmina#431]
I'm trying to get my local freebsd port to build a more recent version (with gtk3 related to #220 )

Using the v1.2.0-rcgit.2 (next) I get the following error:

```
/remmina/src/remmina_masterthread_exec.c:101:10: error: no member named 'sftp_client_confirm_res
ume' in 'union remmina_masterthread_exec_data::<anonymous at /remmina/work/FreeRDP-Remmina-93bf25e/remmina/src/remmina_masterthread_e
xec.h:52:2>'
                                d->p.sftp_client_confirm_resume.retval = remmina_sftp_client_confirm_resume( d->p.sftp_client_confirm_resume.client,
                                ~~~~ ^
```

Thanks

**Comment by giox069** [comment]
This is a bug and I will fix it. In the meanwhile if you try to add libvte and define HAVE_LIBVTE, this should not happen.
As your previous request in issue #220, I'm unable to list all needed libraries, but you can post compilation output here, so we can find what's missing.

**Comment by giox069** [comment]
Take a look also to the Fedora 20/21 compilation guide [here](https://github.com/FreeRDP/Remmina/wiki/Compile-on-Fedora-20): 1st step of the guide installs some needed libraries needed in fedora.

**Comment by mike-pt** [comment]
I'll take a look at the Fedora guide thanks, from the output and since I got as far as this error it seems the decencies needed are found including vte, at least if I choose to build the port with "TERM" support (which I am ):
 remmina-1.2.0 depends on shared library: libvte.so - found (/usr/local/lib/li
bvte.so.9.2800.2)

Wait... maybe I have vte for gtk2?

"vte-0.28.2_2                   Gtk 2 based terminal widget with accessibility and I18N support"

**Comment by mike-pt** [comment]
Fixed with:
 .if ${PORT_OPTIONS:MTERM}
-USE_GNOME+=    vte
+USE_GNOME+=    vte3
 .else

and remmina compiled successfully so at least the needed dependencies are installed, I might need to remove unneeded ones from the port though :)

**Comment by mike-pt** [comment]
I get a compile error with the rdp plugin though:

"CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FREERDP_CHANNELS_LIBRARY"

However the stable port does include this in its patch file:


```
diff -urN cmake/FindFREERDP.cmake cmake/FindFREERDP.cmake
--- cmake/FindFREERDP.cmake	2012-02-11 05:54:23.000000000 +1100
+++ cmake/FindFREERDP.cmake	2014-01-08 02:31:52.000000000 +1100
@@ -14,7 +14,7 @@
 #
 # You should have received a copy of the GNU General Public License
 # along with this program; if not, write to the Free Software
-# Foundation, Inc., 59 Temple Place, Suite 330, 
+# Foundation, Inc., 59 Temple Place, Suite 330,
 # Boston, MA 02111-1307, USA.
 
 find_package(PkgConfig)
@@ -30,7 +30,7 @@
 find_library(FREERDP_GDI_LIBRARY NAMES freerdp-gdi
 	HINTS ${PC_FREERDP_LIBDIR} ${PC_FREERDP_LIBRARY_DIRS})
 
-find_library(FREERDP_KBD_LIBRARY NAMES freerdp-kbd
+find_library(FREERDP_LOCALE_LIBRARY NAMES freerdp-locale
 	HINTS ${PC_FREERDP_LIBDIR} ${PC_FREERDP_LIBRARY_DIRS})
 
 find_library(FREERDP_RAIL_LIBRARY NAMES freerdp-rail
@@ -39,14 +39,14 @@
 find_library(FREERDP_CODEC_LIBRARY NAMES freerdp-codec
 	HINTS ${PC_FREERDP_LIBDIR} ${PC_FREERDP_LIBRARY_DIRS})
 
-find_library(FREERDP_CHANNELS_LIBRARY NAMES freerdp-channels
+find_library(FREERDP_CLIENT_LIBRARY NAMES freerdp-client
 	HINTS ${PC_FREERDP_LIBDIR} ${PC_FREERDP_LIBRARY_DIRS})
 
 include(FindPackageHandleStandardArgs)
 
 find_package_handle_standard_args(FREERDP DEFAULT_MSG FREERDP_LIBRARY FREERDP_INCLUDE_DIR)
 
-set(FREERDP_LIBRARIES ${FREERDP_LIBRARY} ${FREERDP_GDI_LIBRARY} ${FREERDP_KBD_LIBRARY} ${FREERDP_RAIL_LIBRARY} ${FREERDP_CODEC_LIBRARY} ${FREERDP_CHANNELS_LIBRARY})
+set(FREERDP_LIBRARIES ${FREERDP_LIBRARY} ${FREERDP_GDI_LIBRARY} ${FREERDP_LOCALE_LIBRARY} ${FREERDP_RAIL_LIBRARY} ${FREERDP_CODEC_LIBRARY} ${FREERDP_CLIENT_LIBRARY})
 set(FREERDP_INCLUDE_DIRS ${FREERDP_INCLUDE_DIR})
 
 mark_as_advanced(FREERDP_INCLUDE_DIR FREERDP_LIBRARY)
```

The patch seems to still apply, I paste it here in case its useful and/or can be merged.

**Comment by giox069** [comment]
which version of freerdp are you linking against ? Remmina 1.2 will never be able to ling to Freerdp 1.1...

**Comment by giox069** [comment]
FreeRDP 1.2 is the current development version on their master branch, they currently do not provide a github "release" for freerdp 1.2. Remmina 1.2 can only be compiled with FreeRDP 1.2.

**Comment by mike-pt** [comment]
Hum, seems that I have an old one installed:
freerdp-1.1.0_2                Free implementation of Remote Desktop Protocol

Need to grab the github version or see if there another port (its common in freebsd to see a "devel" version on a port, so I might be lucky) In any case I'll see if it compiles fine with 1.2

**Comment by weedy** [comment]
I'm having the same problem on Gentoo
```
[ 76%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_masterthread_exec.c.o
cd /var/tmp/portage/net-misc/remmina-1.2.0_rc3/work/remmina-1.2.0_rc3_build/remmina && /usr/lib64/ccache/bin/x86_64-pc-linux-gnu-gcc  -DHAVE_LIBGCRYPT -DHAVE_LIBSSH -DREMMINA_EXTERNAL_TOOLS_DIR=\"/usr/share/remmina/external_tools\"  -DNDEBUG -march=native -O2 -pipe -mcx16 -msahf -fomit-frame-pointer -fdiagnostics-color=auto  -Wall -fPIC -Wno-unused-result -Wno-unused-but-set-variable -Wno-unused-function -I/var/tmp/portage/net-misc/remmina-1.2.0_rc3/work/Remmina-1.2.0-rcgit.3/. -I/var/tmp/portage/net-misc/remmina-1.2.0_rc3/work/Remmina-1.2.0-rcgit.3/remmina/include -I/usr/include/gtk-3.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0    -o CMakeFiles/remmina.dir/src/remmina_masterthread_exec.c.o -c /var/tmp/portage/net-misc/remmina-1.2.0_rc3/work/Remmina-1.2.0-rcgit.3/remmina/src/remmina_masterthread_exec.c
../../Remmina-1.2.0-rcgit.3/remmina/src/remmina_masterthread_exec.c: In function ‘remmina_masterthread_exec_callback’:
../../Remmina-1.2.0-rcgit.3/remmina/src/remmina_masterthread_exec.c:102:9: error: ‘union <anonymous>’ has no member named ‘sftp_client_confirm_resume’
     d->p.sftp_client_confirm_resume.retval = remmina_sftp_client_confirm_resume( d->p.sftp_client_confirm_resume.client,
         ^
../../Remmina-1.2.0-rcgit.3/remmina/src/remmina_masterthread_exec.c:102:86: error: ‘union <anonymous>’ has no member named ‘sftp_client_confirm_resume’
     d->p.sftp_client_confirm_resume.retval = remmina_sftp_client_confirm_resume( d->p.sftp_client_confirm_resume.client,
                                                                                      ^
../../Remmina-1.2.0-rcgit.3/remmina/src/remmina_masterthread_exec.c:103:10: error: ‘union <anonymous>’ has no member named ‘sftp_client_confirm_resume’
      d->p.sftp_client_confirm_resume.path );
          ^
../../Remmina-1.2.0-rcgit.3/remmina/src/remmina_masterthread_exec.c: In function ‘remmina_masterthread_exec_and_wait’:
../../Remmina-1.2.0-rcgit.3/remmina/src/remmina_masterthread_exec.c:129:80: warning: initialization from incompatible pointer type
  pthread_cleanup_push(remmina_masterthread_exec_cleanup_handler, (void *)d);
                                                                                ^
remmina/CMakeFiles/remmina.dir/build.make:518: recipe for target 'remmina/CMakeFiles/remmina.dir/src/remmina_masterthread_exec.c.o' failed
make[2]: *** [remmina/CMakeFiles/remmina.dir/src/remmina_masterthread_exec.c.o] Error 1
make[2]: Leaving directory '/var/tmp/portage/net-misc/remmina-1.2.0_rc3/work/remmina-1.2.0_rc3_build'
CMakeFiles/Makefile2:99: recipe for target 'remmina/CMakeFiles/remmina.dir/all' failed
make[1]: *** [remmina/CMakeFiles/remmina.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/net-misc/remmina-1.2.0_rc3/work/remmina-1.2.0_rc3_build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by antenore** [comment]
Any news about this? It's quite old so I'm closing it.

Just reopen it if you still have the issue (I'm just cleaning up issues)
